### ISSUE TITLE
Question: The requested resource does not support http method 'POST' when adfs redirects back to wsfed endpoint

### ISSUE THREAD

**Issue by a-tok** [IdentityServer/IdentityServer3.WsFederation#72]
Hello,

I've established a relying party trust between our ADFS and IdentityServer, IdentityServer is the relying party. 
I used the WsFederationAuthenticationOptions to setup the external authentication with ADFS using the metadata generated with the WsFederationAuthenticationPlugin /wsfed/metadata endpoint. I get authenticated successfully, ADFS redirects back to the /wsfed endpoint but the request is of type POST and the result is in the body of the request, causing the "The requested resource does not support http method 'POST'" response. The /wsfed/metadata is a requirement for us, so we can't disable wsfed plugin and establish the trust manually. What am I missing? It seems like a config issue however I can't seem to find any documentation on it. 

Any help is greatly appreciated.

Thank You

**Comment by scottbrady91** [comment]
If Identity Server is configured as a relying party, then it does not need this ws-fed plugin. Instead the ADFS installation should be configured within Identity Server as an external identity provider. See the Adding WS-Federation Identity Providers section of the [Identity Providers documentation](https://identityserver.github.io/Documentation/docsv2/configuration/identityProviders.html).

The metadata endpoint required by `WsFederationAuthenticationOptions` within Identity Server needs to be the metadata endpoint of your ADFS installation, not of identity server.

Unless the issue is happening when you log into identity server using a relying party and your ADFS credentials, in which case you'd be best off showing some of your code and any logs.

**Comment by a-tok** [comment]
Thanks for the reply Scott. I actually used your post as the guide:
https://www.scottbrady91.com/Identity-Server/Identity-Server-3-using-WS-Federation
Unfortunately we need the metadata endpoint and setting up WsFederationAuthenticationOptions doesn't provide one. It looks like I need the combination of the plugin and the WsFederationAuthenticationOptions.
